### ISSUE TITLE
Update for CLDR 28

### ISSUE THREAD

**Issue by govin** [mj1856/TimeZoneNames#10]
I'm using this library to display timezones in friendly format. For "America/Cancun" timezone, the library returns "Central Standard Time". However, "America/Cancun" timezone is now following "Eastern Standard Time". They changed their time zone they were following. How do I update the CLDR database this library is using to the latest one? Can you please update the database and publish a new nuget package? I'm happy to help contribute to updating this library and its database if you can teach me how to do it.

**Comment by mj1856** [comment]
Thanks for the reminder.  Updating is fairly easy, as the data builder downloads the latest CLDR automatically.  You just run the builder then recompile to re-embed the data.

Though you're probably using the Nuget package, so it will help if I update and re-release.

I will update to CLDR 28 soon. It does indeed include the change for `America/Cancun` you mentioned. Thanks.

**Comment by govin** [comment]
Yes, I'm using the nuget package. Thanks!

I'll wait for the updated nuget package.

**Comment by mj1856** [comment]
I'm fixing a few other things while I'm at it. Thanks for your patience.

**Comment by govin** [comment]
Thanks. Appreciate it. Do you have an ETA on when this will be complete?

**Comment by mj1856** [comment]
Version 1.3.0 is published with this, and several other fixes.

However, note I discovered a few things that still need work in #11 and #12.  I decided to go ahead for now, and will fix these in a future version.  Thanks.

**Comment by govin** [comment]
@mj1856 Thanks much for getting this out. Verified the America/Cancun issue we were having is resolved now and it correctly shows "Eastern Standard Time".  Good to know about the known issues.
