### ISSUE TITLE
GetNamesForTimeZone for Belgium

### ISSUE THREAD

**Issue by aakrotov** [mj1856/TimeZoneNames#16]
I found a case where GetNamesForTimeZone throws a NullReference exception.  

GetNamesForTimeZone("UTC+12", "de-DE") returns a set of values as expected and it works with en-US

If you replace Culture with "nl-BE", the above method throws a NullReference exception.

Probably not the only case when this happens, the only one I know of so far, there may be more.  If there is no value, empty string is much better than NullRef which I have to catch.

**Comment by mj1856** [comment]
This is fixed in 2.1.0.  Thanks for reporting!
