### ISSUE TITLE
GetTimeZonesForCountry throws exception with languageCode "en-US"

### ISSUE THREAD

**Issue by DorianGreen** [mj1856/TimeZoneNames#2]
langKey should be used instead of languageCode:

return zones.Select(x => new { Id = x, Names = GetNames(x, languageCode, false) })
                .ToDictionary(x => x.Id, x => x.Names);

**Comment by mj1856** [comment]
Yep!  Looks like I missed unit test for that one.  Will fix shortly.  Thanks!

**Comment by mj1856** [comment]
This is fixed in release 1.2.0.  Thanks!
