### ISSUE TITLE
When using paket as a package manager, protobuf-net needs version 2.0.0.668

### ISSUE THREAD

**Issue by Erbbo** [mj1856/TimeZoneNames#20]
Performed a paket install with the nuget for TimeZoneNames and it specified >= 2.0.0.668 which retrieved  the newest version 2.1. This version errors with "Could not load file or assembly 'protobuf-net' version 2.0.0.668" because it is actually version 2.1.

Maybe just an fyi as I just needed to lock the version to 2.0.0.668.

**Comment by troygrosfield** [comment]
Would be great to get this fixed!

**Comment by troygrosfield** [comment]
This PR is related to this:

- https://github.com/mj1856/TimeZoneNames/pull/19

**Comment by mj1856** [comment]
Just released 3.0.0 for .NET Standard support and removal of protobuf.  Thus, this is no longer applicable.  Thanks.
