### ISSUE TITLE
Netstandard support

### ISSUE THREAD

**Issue by jarroda** [mj1856/TimeZoneNames#21]
I hate to be 'that guy' on your repo... but do you plan on supporting .netstandard as a build target for this library?  Looks like protobuf has support for it, so hopefully it would be a fairly easy port.

**Comment by mj1856** [comment]
I do.  I just haven't gotten to it yet.  And I want to drop the protobuf dependency first.

**Comment by jarroda** [comment]
Sounds great.  In the meantime, I would really like to use your project for a .net core app we are building, so I nearly have your project ported to netstandard.  I have the main `TimeZoneNames` project and the DataBuilder projects completely converted and working xplat, and I regenerated the `tz.dat` successfully on OSX as a test.  I still plan on porting the testing project.

If you are interested in these changes, I would be happy to send you a PR.  If not, we will just use my fork for now and will switch back to your package when you have made your changes.

**Comment by DDN-Shep** [comment]
Looking forward to this too as I need it for .NET Core project. 

This sort of library is surprisingly quite rare despite how many people want a time zone abbreviation!

**Comment by sirishs** [comment]
I am on the other side of the boat, I want to use with regular .net45+ framework without .net core, so it will be great if we can get rid of protobuf dependency as mj called out earlier and publish a version without that, then I will be able to consume this package. 

Currently I am getting a runtime exception stating: 'blah... Could not load file or assembly 'System.Core, Version=2.0.5.0... blah'

Yes, it is surprising that this is only nuget package which has this wonderful timezone localization feature. :) Thanks for this amazing package!

**Comment by mj1856** [comment]
Thanks for the feedback.  Yes, will do.  Just been busy.  Thanks for being patient.  :)

**Comment by mj1856** [comment]
Done with 3.0.0.  Thanks.
