### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DanAvni** [mj1856/TimeZoneNames#22]
Hi,

Please add a function that returns the country name (in a specific language) based on the time zone id
I have "Asia/Jerusalem" for example and I want to display the country name as Israel and the clock name (which GetNamesForTimeZone already provides)
Or maybe extend the returned value from GetNamesForTimeZone so it will also contain the country name

**Comment by mj1856** [comment]
Sorry, that's beyond the scope of this project.
