### ISSUE TITLE
inconsistent names

### ISSUE THREAD

**Issue by DanAvni** [mj1856/TimeZoneNames#23]
when asking for us timezones valid today I get
`TimeZoneNames.TZNames.GetTimeZonesForCountry("us","en",Date.UtcNow)`
I get two mountain time zones
America/Phoenix Mountain Time (Phoenix) 
America/Denver Mountain Time (Denver) 

however when asking for the name of 
```
TimeZoneNames.TZNames.GetNamesForTimeZone("America/Denver","en")
TimeZoneNames.TZNames.GetNamesForTimeZone("America/Phoenix","en")
```
I get for both a name of "Mountain Time"

is this by design or a bug?

**Comment by mj1856** [comment]
Sorry for the delayed response.

It's by design, in that `GetTimeZoneForCountry` appends the city name when necessary to disambiguate results.  `GetNamesForTimeZone` simply returns the raw result.
