### ISSUE TITLE
Dependency on Newtonsoft.Json

### ISSUE THREAD

**Issue by jnyrup** [mj1856/TimeZoneNames#30]
I see that the new version depends on Newtonsoft.Json v10.0.3.
Is that version picked, because that's the version the `DataExtractor` uses, or does `TimeZoneData` also need v10.0.3/newest to deserialize the data again?

**Comment by mj1856** [comment]
It does need to be used on both sides, yes.  I had just picked the most current version when I installed, but I can probably relax that a bit.  I'll post an update shortly, lowering the version requirement to the minimum supported.  Thanks.

**Comment by mj1856** [comment]
Ok.  I lowered the Newtonsoft.Json dependency to >=5.0.5 for .NET Framework and to >=9.0.1 for .NET Standard.

Released as version 3.1.0.
https://www.nuget.org/packages/TimeZoneNames/3.1.0

**Comment by jnyrup** [comment]
Maybe a silly question, but have you deployed the right build to NuGet?
On https://www.nuget.org/packages/TimeZoneNames/3.1.0 it says that .netstandard 1.1 has a dependency on newtonsoft 6.0.2. It's the same in the nuspec when downloading the nupkg.
Shouldn't it be v9.0.1 as per b43d692a3cb685a228dbe6dfccbc345561fa24ec

**Comment by jnyrup** [comment]
@mj1856 Just to verify: 
I just created .netstandard1.1 project and tried to install TimeZoneNames 3.1.0, but it failed with:
Package Newtonsoft.Json 6.0.2 is not compatible with netstandard1.1 (.NETStandard,Version=v1.1).

**Comment by mj1856** [comment]
Yeah, I must have screwed up something.  Republished as 3.1.1.  Looks good now I think.
