### ISSUE TITLE
Upgrade from 1.2.1 to 3.1.1

### ISSUE THREAD

**Issue by joviledog** [mj1856/TimeZoneNames#35]
We are using  var tzNamesAbbrv = tzn.TimeZoneNames.GetAbbreviationsForTimeZone(timeZoneInfoId, "en-US"); in 1.2.1
What is the equivalent way to do that in V3.1.1  Also input timeZoneId of W. Europe Standard Time would output CET as the standard time.  

I want to see if V.3.1.1 would provide a better mapping.

**Comment by mj1856** [comment]
That API has not changed.  On the abbreviation output, see my comments on #25.  Thanks.
