### ISSUE TITLE
Strongly signed

### ISSUE THREAD

**Issue by mrbeck02** [mj1856/TimeZoneNames#38]
Could you please provide a strongly named solution for this like you do for TimeZoneConverter?

Thanks

**Comment by mj1856** [comment]
I don't provide a strong named assembly.  Someone else appears to be publishing that to nuget.

This has been asked before in #26, and my reasoning still applies.  I do not generally provide strongly named assemblies for any of my OSS projects.

Additionally, see:
- https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i

- https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/


Generally, strong naming is not a thing anymore.

**Comment by mj1856** [comment]
If you *must* have strong naming, there are a few projects that allow you to do it yourself.

https://www.nuget.org/packages/Nivot.StrongNaming/

https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/

**Comment by sonergonul** [comment]
Also #54
