### ISSUE TITLE
BCL standard name for AUS Eastern Standard Time

### ISSUE THREAD

**Issue by gooderic1977** [mj1856/TimeZoneNames#42]
I was expecting TZNames.GetNamesForTimeZone return a result contain a valid BCL standard timezone name, e.g.:

TZNames.GetNamesForTimeZone("Australia/Sydney","en-US").Standard -> AUS Eastern Standard Time

However, I got a result: "Australia Eastern Standard Time" instead.  This is not a valid standard timezone name

**Comment by mj1856** [comment]
I think you are confusing names for identifiers.  This library produces human-readable localizable names, for display to end users.  If you just want conversion to Microsoft (BCL) standard time zone identifiers, use [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter) instead.

I maintain both libraries, and TimeZoneNames takes a dependency on TimeZoneConverter, so you probably already have it.

```csharp
    string tz = TZConvert.IanaToWindows("Australia/Sydney"); //=> "AUS Eastern Standard Time"
```
