### ISSUE TITLE
Dependency on newer TimeZoneConverter

### ISSUE THREAD

**Issue by jnyrup** [mj1856/TimeZoneNames#43]
Hi Matt

I'm sorry to bother you again with this dependency hassle again.
Would you mind upgrading TimeZoneNames to depend on the new TimeZoneConverter?

**Comment by mj1856** [comment]
Yeah, will do shortly.

Need to get to the bottom of the dependency problem here though also.  They should be able to rev independently if semver compatible.

**Comment by mj1856** [comment]
Also, you could add a binding redirect.  See my notes in mj1856/TimeZoneConverter#16.

The real fix would be to figure out how to *force* a binding redirect be added automatically when you pull in the package from Nuget.  If anyone knows how to do that, please let me know.  Thanks.

**Comment by mj1856** [comment]
I'm going to leave it as-is for now to help troubleshoot the root cause.  Please add the binding redirect to your application to work around for now.  Thanks.

**Comment by mj1856** [comment]
Still don't have a great answer for the long term, but updated to TimeZoneConverter 2.4.1 in TimeZoneNames 3.3.3.

**Comment by mj1856** [comment]
Given we have strong name signing now, I believe this issue is resolved.  If not, please let me know.  Thanks.
