### ISSUE TITLE
Error trying to install NuGet package

### ISSUE THREAD

**Issue by rrectenwald** [mj1856/TimeZoneNames#44]
Install-Package : 'TimeZoneConverter' already has a dependency defined for 'System.Collections'.
At line:1 char:1
+ Install-Package TimeZoneConverter
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by mj1856** [comment]
That is really strange.  Can you tell me about your environment?  Are you using .Net Framework or .Net Core and what version?  Also what version of nuget and visual studio if using it?  Thanks.

**Comment by rrectenwald** [comment]
I’m using .Net 4.0 and VS2012, Package Manager Console Host Version 2.6.40627.9000

The strange thing is I can build the source in VS 2017 and reference the dll in my app with no issues but if I load it via nuget I get the error. I just wanted to let you know in case other users are experiencing the same issue.

**Comment by mj1856** [comment]
Thanks for the details.  Can you please update to the latest version of NuGet from the `Tools` - `Extensions and Updates` menu and see if that resolves the problem?  Also be sure you have any updates to Visual Studio itself installed.  I haven't worked with VS2012 in some time, so I'm not sure if this is a know/fixed issue already or not.

**Comment by mj1856** [comment]
Closing due to no response.  If the issue persists, let me know and I'll reopen.  Thanks.
