### ISSUE TITLE
Move to Newtonsoft.JSON 11

### ISSUE THREAD

**Issue by appqui** [mj1856/TimeZoneNames#48]
Version 11 has no dependencies on NETStandard 2.0, while 9 has lots of them. 

Make sense or I am missing something?

**Comment by mj1856** [comment]
Indeed, it looks like with Newtonsoft.JSON 11.0.1, .NET Standard 2.0 became a direct target.  Thus, there are some efficiencies if my 2.0 target uses 11.0.1 as a minimum dependency version.  I will make this change shortly.

**Comment by mj1856** [comment]
Done in version 3.3.3.  Thanks.
