### ISSUE TITLE
TimeZoneNames 3.4.0 not working with TimeZoneConverter 3.0.0

### ISSUE THREAD

**Issue by fcorbeil** [mj1856/TimeZoneNames#55]

**Comment by mj1856** [comment]
Yep.  Will be a couple of days, I'm on vacation.  Thanks.

**Comment by fcorbeil** [comment]
Thank you for the fast reply and enjoy your vacation!

**Comment by mj1856** [comment]
This is complete in version 4.0.0.  Thanks.
