### ISSUE TITLE
Windows time zones have been updated

### ISSUE THREAD

**Issue by tomkludy** [mj1856/TimeZoneNames#56]
Microsoft renamed the "Sao Tome Standard Time" time zone (now it is UTC+01:00 rather than UTC+00:00) and added "Qyzylorda Standard Time" time zone.

Updated data file is available at https://raw.githubusercontent.com/tomkludy/TimeZoneWindowsResourceExtractor/master/TZResScraper/tzinfo.json

**Comment by mj1856** [comment]
Thanks.  I'll update the display names data in the next release (soon).

**Comment by mj1856** [comment]
Completed in version 4.0.1.  Thanks again!
