### ISSUE TITLE
CET timezone shown as invalid 

### ISSUE THREAD

**Issue by unuunc** [mj1856/TimeZoneNames#6]
I am getting all timezone from Noda by using NodaTime.DateTimeZoneProviders.Tzdb.Ids and converting to Timezone names. it fails for "CET". Can you check if all TZDb Id's are supported ?

**Comment by mj1856** [comment]
Thanks for reporting.  I'll go through and make some tests that it should support all valid TZDB Ids, including the backwards compatibility ones.

In the meantime, I suggest you omit any IDs that don't contain a `/` character - except perhaps `"UTC"`.

**Comment by mj1856** [comment]
All IANA and Windows IDs should return *something* in version 1.3.0.  Hopefully it's the expected string.
