### ISSUE TITLE
"Yukon Standard Time" not recognized as a valid IANA time zone name, or has no equivalent Windows time zone.

### ISSUE THREAD

**Issue by theonlychunsta** [mj1856/TimeZoneNames#60]
![image](https://user-images.githubusercontent.com/25270217/93103936-3ba06880-f67b-11ea-8b66-c660eee26d36.png)

A new timezone has been added by Windows in one of their recent updates, causing this exception to be thrown.

**Comment by mj1856** [comment]
Thanks.  I just added this to TimeZoneConverter 3.3.0, but I need to update TimeZoneNames for it as well.

**Comment by Grandizer** [comment]
Wow. glad I found this.  So, when will 3.3.1 be out?  :)

**Comment by Grandizer** [comment]
Also, perhaps as a future enhancement (after this fix goes out) if you could make a `TryGetDisplayNameForTimeZone` so it won't crash this code I inherited.

**Comment by mj1856** [comment]
I'll have an update for TimeZoneNames out soon.  I'm working on it.  The Windows display names have to be re-built via [TimeZoneWindowsResourceExtractor](https://github.com/tomkludy/TimeZoneWindowsResourceExtractor) first.  (It takes some time to get the VM with all the language packs installed and updated before extraction.)

**Comment by mj1856** [comment]
Also, by its current design - `GetDisplayNameForTimeZone` should have returned `null` instead of throwing an exception.  I'll fix that.

Not planning on adding `TryGet*` methods to this library, at least not now.

**Comment by mj1856** [comment]
Both are fixed in version 4.1.0.  Thanks!

**Comment by Grandizer** [comment]
Good Job, I will grab it later today.  Thank you.
