### ISSUE TITLE
Internal data format

### ISSUE THREAD

**Issue by mj1856** [mj1856/TimeZoneNames#7]
Originally, I used protobuf to get the job done quickly while still ensuring a compact internal representation.   However, I'd rather not have the external dependency.

Need to explore other options, such as a custom format, gzip compression, etc.

**Comment by barrycarter** [comment]
Would this include the possibility of a CSV or similar file for those of us not using C#?

**Comment by mj1856** [comment]
Sorry, but no. I'm not prepared to support that as a direct consumable.  However, you could indeed use the library to generate such a file for a particular language.

**Comment by barrycarter** [comment]
To anyone else interested in this issue, I've now sort of done this at:

https://github.com/barrycarter/bcapps/blob/master/ASTRO/tz2name.txt

**Comment by mj1856** [comment]
Switched to GZipped json instead of protobuf with release 3.0.0
